
name: CI Pipeline

on: [push]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Lint with flake8
      run: flake8 . --count --show-source --statistics
    - name: Run tests
      run: pytest